@startuml
title PISP Linking: Authentication
!include participants.iuml

... Alice chooses DFSP A ...

autonumber 1 "<b>DISC-#</b>"
Alice -> App: My account is with DFSP A.
deactivate Alice
activate App

autonumber 1 "<b>AUTH-#</b>"
group Authentication: Prove to the DFSP that you are their customer.
    App -> Alice: OK. We'll open a direct you to DFSP A's login URL.\nIt will redirect to us when you're done.
    deactivate App
    activate Alice
    Alice -> DFSP: ""GET dfspa.example.com/login?redirect=pisp.example.com/token""
    ' TODO: Clarify what parameters are in the redirect URL
    activate DFSP
    DFSP --> Alice: 200 OK, ""<html><form ...> ...</html>""
    deactivate DFSP
    Alice -> DFSP: ""POST dfspa.example.com/login { username: Alice, password: ~*~*~*~*~*~* }""
    deactivate Alice
    activate DFSP
    DFSP -> DFSP: Verify credentials
end

@enduml