@startuml
autonumber 0

title PISP Linking: Delegation
!include participants.iuml

... Alice logs in with credentials directly to DFSP A ...

autonumber 4 "<b>AUTH-#</b>"
Alice -> IP: ""POST dfspa.example.com/login { username: Alice, password: ~*~*~*~*~*~* }""
activate Alice
activate IP
IP -> IP: Verify\ncredentials

autonumber 1 "<b>DELE-#</b>"
group Delegation: Provide a secret the PISP can use to act on the user's behalf.
    IP -> Switch: What's the redirect\ndomain for PISP?
    activate Switch
    Switch --> IP: 202 I'll get back to you.
    deactivate IP
    Switch -> ALS: What's the redirect\ndomain for PISP?
    activate ALS
    ALS --> Switch: It's ""pisp.example.com"".
    deactivate ALS
    Switch -> IP: The domain for PISP is\n""pisp.example.com""
    activate IP
    IP --> Switch: 200 OK, got it.
    ' TODO: Does the IP validate the domain here?
    deactivate Switch
    IP --> Alice: ""302 pisp.example.com/token?secret=~*~*~*~*""
    deactivate Alice
    deactivate IP
    Alice -> Server: ""GET pisp.example.com/token?secret=~*~*~*~*""
    activate Alice
    activate Server
    Server -> Server: Store access token\nfor future use.
    Server --> Alice: 200 OK, got it.
    deactivate Alice
end

@enduml